### ISSUE TITLE
New feature: be able to provision separate section(s) based on label(s)

### ISSUE THREAD

**Issue by yarikoptic** [con/solidation#17]
E.g.

```yaml
custom_sections:
- name: Easy work needing help
  types: [pull, issue]
  labels: easy, contribution-desired
```

to create a section which would collate Pull requests and Issues which have both labels `easy` and `contribution-desired`.
It would then be useful to annotate/be able to find work which anyone in the team could pick up "when bored" or just to improve the greenness of their github profiles.

as for selection, I wonder if may be it could be generalized a little more exposing internal structure but making it also flexible

```
  condition: 'easy' in thing.labels and 'contribution-desired' in thing.labels"
```
where `thing` would  be an issue (from `self.active_issues`) or a PR (from `self.open_prs`).

WDYT @jwodder ?
