### ISSUE TITLE
repository: make it possible to consider issues/PRs only for known members

### ISSUE THREAD

**Issue by yarikoptic** [con/solidation#19]
https://github.com/con/solidation-con/blob/master/reports/2023-02-20.md#non-con-member-issues-activeopened-in-the-last-7-days shows the tricky use case we have.  I think we should keep monitoring our occasional work within repositories such as `dandi-archive`. But there we are not main maintainers/developers, so 
- we aren't really interested in listing all of the issues filed by main developers as issues from someones who "is not from CON"
- we are interested in all issues/PRs which fall in the other categories and which are owned or assigned to CON members.

I see two possible ways we could "specify" such "special nature" of some repos

- per repo, do similar to #18 - add ability to specify per each repo some attribute like `foreign: True` thus indicating that we are not interested to "own"/attend to all the issues/PRs 
- add higher level `foreign_repositories` listing, so it would make it easy to just list all of those separately.

WDYT @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic To be clear, marking a repository as "foreign" means that only activity from project members should be considered, correct?  I would prefer to indicate this via a `foreign: true` field on elements of `repositories`.

**Comment by yarikoptic** [comment]
> @yarikoptic To be clear, marking a repository as "foreign" means that only activity from project members should be considered, correct? 

Correct. Only activity (created by them) and assigned items (PRs/issues) should be considered.

> I would prefer to indicate this via a `foreign: true` field on elements of `repositories`.

ok.  I thought it might then be too verbose/tedious, but I think

<details>
<summary>it would be quite ok if we adopt for CON (I even added it to be specified on organization level so someone could just do it at that level as well)</summary> 

```yaml

project: CON

organizations:
  - con
  - name: NeurodataWithoutBorders  # only few repos and we are present throughout
    foreign: True

repositories:
  # might got away since mostly autogenerated but has issues ATM:
  - con/versations-archive
  - dandi/dandi-api-webshots-tools
  - dandi/dandi-archive
  - dandi/dandi-cli
  - name: dandi/dandi-hub
    foreign: true
  - dandi/dandi-schema
  - dandi/dandisets
  - dandi/dandisets-healthstatus
  - dandi/example-notebooks
  - dandi/handbook
  - dandi/helpdesk
  - dandi/zarr_checksum
  - name: datalad/datalad
    foreign: true
  - datalad/datalad-container
  - datalad/datalad-crawler
  - datalad/datalad-deprecated
  - datalad/datalad-fuse
  - datalad/datalad-installer
  - datalad/datalad-neuroimaging
  - datalad/datalad-registry
  - datalad/datasets.datalad.org
  - datalad/git-annex
  - neurodebian/dockerfiles
  - neurodebian/neurodebian
  - nipy/heudiconv
  - ReproNim/containers
  - ReproNim/reproin
  - ReproNim/reproman
  - ReproNim/reprostim

  # really external but where we are involved/maintainers etc
  - name: DanielDent/git-annex-remote-rclone  # yarikoptic
    foreign: true
  - TheChymera/neuralynx_nwb  # TheChymera, yarikoptic

  - name: bids-standard/bids-specification  # yarikoptic, TheChymera
    foreign: True 
  - name: hdmf-dev/hdmf
    foreign: true
  - name: fsspec/filesystem_spec
    foreign: true

  # packaging feedstocks -- we need to be alerted and keep them clean etc
  - conda-forge/annexremote-feedstock
  - conda-forge/dandi-feedstock
  - conda-forge/git-annex-feedstock

members:
  - yarikoptic
  - andycon
  - jwodder
  - TheChymera
  - asmacdo
  - candleindark
```
</details>

Let's do it!
